# Generated by Django 2.0.5 on 2018-05-14 12:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authpage', '0002_auto_20180513_1919'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='date_joined',
        ),
    ]
